### ISSUE TITLE
Help! The is something happening that does not allow me to update Randy's picture in the 4 square box pictures on the homepage. 

### ISSUE THREAD

**Issue by radiantproject** [victor-rocha/radiant#24]
I tried uploading 2 new versions of the pics in the 4 square box pictures and somehow it only allows me to update David's (radiant human 13). I went to Radiant Humans -> Nothing just happens to me -> blurb image... and it won't show up for some reason. Instead it is showing me the pictures that I updated in David's (radiant human 13) admin page

**Comment by radiantproject** [comment]
We figured out that any of those 4 squares on the homepage pictures can only be controlled by David's radiant human admin page, and we can't fix anything from Randy's admin page anymore (which is now called, Nothing Just Happens to Me). This has caused a glitch in the system because the pictures just double up now for some reason, instead of all being different pictures. Can we fix this bug as soon as you get the chance?

**Comment by victor-rocha** [comment]
This is not a bug but a user error. it is important to actually enter release dates for each one of the episodes. https://www.theradiantproject.com/admin/profiles/radianthuman/. We calculate what the current episode is and what the next episode is based on the release date and status. If you want this to work, you will need to enter approximate or real release dates to all of the episodes.

**Comment by radiantproject** [comment]
Okay thank you, makes sense. I now have all of our release dates so I will update and take care of this issue.
