### ISSUE TITLE
Desperately need to hook up our website with google analytics so we can see how people interact with the site/how many people visit. I've pasted the analytics code below- we just need it embedded.

### ISSUE THREAD

**Issue by radiantproject** [victor-rocha/radiant#26]
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-75628205-1', 'auto');
  ga('send', 'pageview');

</script>

**Comment by victor-rocha** [comment]
I had setup analytics and granted accessed to radianthive@gmail.com (an invitation should have been sent) a long time ago. This morning, I added kate@theradiantproject.com too (check your email, please). Regretfully, I won't be able to help with any of the other issues.

PS. When filing an issue in github, please use the description field to actually describe the issue. It is hard to heard when the description is in the title of the issue. 

@radiantproject
